import { cellKey, createOozeDemoProject, validateProject } from './spriteData'
import type { LayerCellMap, SpriteFrame, SpriteProject } from './spriteTypes'

const FRAME_SPECS = [
  {
    id: 'ooze-melee-windup',
    name: 'Windup',
    bodyX: 15,
    bodyY: 20,
    bodyRx: 6.8,
    bodyRy: 4.4,
    tendril: [
      [13, 18],
      [10, 16],
      [8, 18],
    ],
    hitbox: { x: 9, y: 15, width: 15, height: 10 },
    notes: 'Squash back before the swipe. Keep the anchor planted.',
  },
  {
    id: 'ooze-melee-lunge',
    name: 'Lunge',
    bodyX: 17,
    bodyY: 20,
    bodyRx: 7.8,
    bodyRy: 4.1,
    tendril: [
      [20, 17],
      [24, 15],
      [27, 16],
    ],
    hitbox: { x: 10, y: 15, width: 20, height: 10 },
    notes: 'Stretch forward. The strike starts reading outside the body silhouette.',
  },
  {
    id: 'ooze-melee-contact',
    name: 'Contact',
    bodyX: 18,
    bodyY: 20,
    bodyRx: 7.1,
    bodyRy: 4.3,
    tendril: [
      [21, 17],
      [26, 14],
      [31, 15],
    ],
    hitbox: { x: 10, y: 14, width: 22, height: 11 },
    notes: 'Impact frame with the longest reach and bright contact pixels.',
  },
  {
    id: 'ooze-melee-recover',
    name: 'Recover',
    bodyX: 16,
    bodyY: 21,
    bodyRx: 7.0,
    bodyRy: 3.9,
    tendril: [
      [20, 18],
      [22, 18],
      [23, 19],
    ],
    hitbox: { x: 9, y: 16, width: 17, height: 9 },
    notes: 'Retract the tendril and settle the body back toward idle.',
  },
] as const

export function createOozeMeleeAttackProject(name = 'Ooze Melee Attack'): SpriteProject {
  const project = createOozeDemoProject(name)
  const frames = FRAME_SPECS.map((spec, index) =>
    createOozeMeleeFrame({
      ...spec,
      durationMs: index === 2 ? 80 : 110,
    }),
  )

  const nextProject: SpriteProject = {
    ...project,
    id: `spritewrite-${slugifyProjectId(name)}`,
    name,
    description: 'Editable four-frame ooze melee attack sprite asset.',
    animations: [{ id: 'melee_attack', name: 'Melee Attack', fps: 10, frameIds: frames.map((frame) => frame.id) }],
    frames,
    metadata: {
      ...project.metadata,
      defaultAnimationId: 'melee_attack',
      notes:
        'Generated by the SpriteWrite ooze melee recipe: windup, lunge, contact, and recover frames with a stable anchor and explicit hitboxes.',
    },
  }

  const validation = validateProject(nextProject)
  if (!validation.valid) {
    throw new Error(`Generated ooze melee project is invalid: ${validation.errors.join('; ')}`)
  }

  return nextProject
}

function createOozeMeleeFrame({
  id,
  name,
  durationMs,
  bodyX,
  bodyY,
  bodyRx,
  bodyRy,
  tendril,
  hitbox,
  notes,
}: (typeof FRAME_SPECS)[number] & { durationMs: number }): SpriteFrame {
  const cells: LayerCellMap = {}
  drawShadow(cells, bodyX)
  drawTendril(cells, tendril)
  drawBody(cells, bodyX, bodyY, bodyRx, bodyRy)
  drawFaceAndCore(cells, bodyX, bodyY, name)

  if (name === 'Contact') {
    drawImpact(cells)
  }

  return {
    id,
    name,
    durationMs,
    notes,
    tags: ['ooze', 'melee', 'attack'],
    anchor: { x: 16, y: 25 },
    hitbox,
    layers: [
      {
        id: 'base',
        name: 'Base',
        group: 'Art',
        visible: true,
        exportable: true,
        editable: true,
        opacity: 1,
        blendMode: 'normal',
        cells,
      },
    ],
  }
}

function drawShadow(cells: LayerCellMap, centerX: number) {
  ellipse(cells, centerX, 25, 8, 1.6, 'shadow')
}

function drawBody(cells: LayerCellMap, centerX: number, centerY: number, radiusX: number, radiusY: number) {
  for (let y = Math.floor(centerY - radiusY) - 1; y <= Math.ceil(centerY + radiusY) + 1; y += 1) {
    for (let x = Math.floor(centerX - radiusX) - 1; x <= Math.ceil(centerX + radiusX) + 1; x += 1) {
      const distance = ((x - centerX) / radiusX) ** 2 + ((y - centerY) / radiusY) ** 2
      if (distance > 1) {
        continue
      }

      if (distance > 0.72 || y >= centerY + radiusY - 0.5) {
        set(cells, x, y, 'outline')
      } else if (y < centerY - 1.5 || x < centerX - 2) {
        set(cells, x, y, 'slime_light')
      } else {
        set(cells, x, y, 'slime_mid')
      }
    }
  }
}

function drawTendril(cells: LayerCellMap, points: readonly (readonly [number, number])[]) {
  for (let index = 0; index < points.length - 1; index += 1) {
    const [fromX, fromY] = points[index]
    const [toX, toY] = points[index + 1]
    line(cells, fromX, fromY, toX, toY, 'outline', 2)
    line(cells, fromX, fromY, toX, toY, 'slime_mid', 1)
  }

  const [tipX, tipY] = points[points.length - 1]
  ellipse(cells, tipX, tipY, 2.2, 1.8, 'outline')
  ellipse(cells, tipX, tipY, 1.2, 0.9, 'slime_light')
}

function drawFaceAndCore(cells: LayerCellMap, centerX: number, centerY: number, frameName: string) {
  const lookOffset = frameName === 'Windup' ? -1 : 1
  set(cells, centerX - 2 + lookOffset, centerY - 2, 'core')
  set(cells, centerX + 2 + lookOffset, centerY - 2, 'core')
  set(cells, centerX - 1 + lookOffset, centerY + 1, 'outline')
  set(cells, centerX + lookOffset, centerY + 1, 'outline')
  set(cells, centerX + 1 + lookOffset, centerY + 1, 'outline')
}

function drawImpact(cells: LayerCellMap) {
  ;[
    [30, 12],
    [31, 12],
    [29, 13],
    [31, 17],
    [30, 18],
  ].forEach(([x, y]) => set(cells, x, y, 'slime_highlight'))
}

function ellipse(cells: LayerCellMap, centerX: number, centerY: number, radiusX: number, radiusY: number, colorId: string) {
  for (let y = Math.floor(centerY - radiusY); y <= Math.ceil(centerY + radiusY); y += 1) {
    for (let x = Math.floor(centerX - radiusX); x <= Math.ceil(centerX + radiusX); x += 1) {
      if (((x - centerX) / radiusX) ** 2 + ((y - centerY) / radiusY) ** 2 <= 1) {
        set(cells, x, y, colorId)
      }
    }
  }
}

function line(
  cells: LayerCellMap,
  fromX: number,
  fromY: number,
  toX: number,
  toY: number,
  colorId: string,
  thickness: number,
) {
  const steps = Math.max(Math.abs(toX - fromX), Math.abs(toY - fromY))
  for (let step = 0; step <= steps; step += 1) {
    const x = Math.round(fromX + ((toX - fromX) * step) / steps)
    const y = Math.round(fromY + ((toY - fromY) * step) / steps)
    ellipse(cells, x, y, thickness, thickness, colorId)
  }
}

function set(cells: LayerCellMap, x: number, y: number, colorId: string) {
  if (x < 0 || y < 0 || x >= 32 || y >= 32) {
    return
  }

  cells[cellKey(x, y)] = colorId
}

function slugifyProjectId(value: string): string {
  return (
    value
      .trim()
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '') || 'ooze-melee-attack'
  )
}
